export const CREATE_ORDER = "CREATE_ORDER";
export const EDIT_ORDER = "EDIT_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const GET_ORDER = "GET_ORDER";
export const ERROR_IN_ORDER = "ERROR_IN_ORDER";
export const GET_ALLL_ORDER = "GET_ALLL_ORDER";

export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ALLL_ORDER_SUCCESS = "GET_ALLL_ORDER_SUCCESS";